run:
  timeout: 5m
linters:
  enable:
    - govet
    - gofmt
    - staticcheck
    - errcheck
    - gocritic
    - funlen
    - gocyclo
linters-settings:
  funlen:
    lines: 130
    statements: 60
  gocyclo:
    min-complexity: 15
